// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYmieTTIpfmTpaHGMATHDLzgMXogsgDJY',
    appId: '1:778647479714:web:20316a91aa756556147efb',
    messagingSenderId: '778647479714',
    projectId: 'hockeyapp-c849f',
    authDomain: 'hockeyapp-c849f.firebaseapp.com',
    storageBucket: 'hockeyapp-c849f.firebasestorage.app',
    measurementId: 'G-HKYVRRT7H6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnEIqb4Cofi-uQcSrcW2PuTg0SER7h6wk',
    appId: '1:778647479714:android:a5bed62f1bc2f16c147efb',
    messagingSenderId: '778647479714',
    projectId: 'hockeyapp-c849f',
    storageBucket: 'hockeyapp-c849f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTolG1KLGpdCYcyzhLukeBO1JPvFOshI4',
    appId: '1:778647479714:ios:cda1f0f4d5b199d3147efb',
    messagingSenderId: '778647479714',
    projectId: 'hockeyapp-c849f',
    storageBucket: 'hockeyapp-c849f.firebasestorage.app',
    iosClientId: '778647479714-h7hbumsfvnd84ip00h9649se8kn9aua0.apps.googleusercontent.com',
    iosBundleId: 'com.example.hockeyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTolG1KLGpdCYcyzhLukeBO1JPvFOshI4',
    appId: '1:778647479714:ios:cda1f0f4d5b199d3147efb',
    messagingSenderId: '778647479714',
    projectId: 'hockeyapp-c849f',
    storageBucket: 'hockeyapp-c849f.firebasestorage.app',
    iosClientId: '778647479714-h7hbumsfvnd84ip00h9649se8kn9aua0.apps.googleusercontent.com',
    iosBundleId: 'com.example.hockeyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYmieTTIpfmTpaHGMATHDLzgMXogsgDJY',
    appId: '1:778647479714:web:e17a43469b41308c147efb',
    messagingSenderId: '778647479714',
    projectId: 'hockeyapp-c849f',
    authDomain: 'hockeyapp-c849f.firebaseapp.com',
    storageBucket: 'hockeyapp-c849f.firebasestorage.app',
    measurementId: 'G-VXTSC3FF6S',
  );
}
